#ifndef __ECG_GPIO_H__
#define __ECG_GPIO_H__

#define ACTIVE_LOW			0
#define ACTIVE_HIGH			1

#define DEFAULT_LOW			0
#define DEFAULT_HIGH		1
#define DEFAULT_NOT_USED	2

#define GPIO_ADS_N_CS_PORT          GPIO_PORTA_BASE
#define GPIO_ADS_N_CS_PIN           GPIO_PIN_3
#define GPIO_ADS_N_CS_DIR           GPIO_DIR_MODE_OUT
#define GPIO_ADS_N_CS_DEFAULT       GPIO_PIN_3

#define GPIO_ADS_N_DRDY_PORT        GPIO_PORTB_BASE
#define GPIO_ADS_N_DRDY_PIN         GPIO_PIN_5
#define GPIO_ADS_N_DRDY_DIR         GPIO_DIR_MODE_IN
#define GPIO_ADS_N_DRDY_DEFAULT     DEFAULT_NOT_USED

#define GPIO_ADS_N_RESET_PORT       GPIO_PORTB_BASE
#define GPIO_ADS_N_RESET_PIN        GPIO_PIN_6
#define GPIO_ADS_N_RESET_DIR        GPIO_DIR_MODE_OUT
#define GPIO_ADS_N_RESET_DEFAULT    GPIO_PIN_6

#define GPIO_ADS_START_PORT         GPIO_PORTB_BASE
#define GPIO_ADS_START_PIN          GPIO_PIN_7
#define GPIO_ADS_START_DIR          GPIO_DIR_MODE_OUT
#define GPIO_ADS_START_DEFAULT      ~GPIO_PIN_7

#define GPIO_BT_N_SHDN_PORT         GPIO_PORTC_BASE
#define GPIO_BT_N_SHDN_PIN          GPIO_PIN_4
#define GPIO_BT_N_SHDN_DIR          GPIO_DIR_MODE_OUT
#define GPIO_BT_N_SHDN_DEFAULT      ~GPIO_PIN_4

#define GPIO_LED0_PORT              GPIO_PORTF_BASE
#define GPIO_LED0_PIN               GPIO_PIN_0
#define GPIO_LED0_DIR               GPIO_DIR_MODE_OUT
#define GPIO_LED0_DEFAULT           ~GPIO_LED0_PIN

#define GPIO_LED1_PORT              GPIO_PORTF_BASE
#define GPIO_LED1_PIN               GPIO_PIN_1
#define GPIO_LED1_DIR               GPIO_DIR_MODE_OUT
#define GPIO_LED1_DEFAULT           ~GPIO_PIN_1

#define GPIO_LED2_PORT              GPIO_PORTF_BASE
#define GPIO_LED2_PIN               GPIO_PIN_2
#define GPIO_LED2_DIR               GPIO_DIR_MODE_OUT
#define GPIO_LED2_DEFAULT           ~GPIO_PIN_2

#define GPIO_PSWITCH_PORT           GPIO_PORTD_BASE
#define GPIO_PSWITCH_PIN            GPIO_PIN_1
#define GPIO_PSWITCH_DIR            GPIO_DIR_MODE_IN
#define GPIO_PSWITCH_DEFAULT        DEFAULT_NOT_USED

#define GPIO_PS1V8_EN_PORT          GPIO_PORTF_BASE
#define GPIO_PS1V8_EN_PIN           GPIO_PIN_2
#define GPIO_PS1V8_EN_DIR           GPIO_DIR_MODE_OUT
#define GPIO_PS1V8_EN_DEFAULT       GPIO_PIN_2

#define GPIO_PS3V3_EN_PORT          GPIO_PORTM_BASE
#define GPIO_PS3V3_EN_PIN           GPIO_PIN_0
#define GPIO_PS3V3_EN_DIR           GPIO_DIR_MODE_OUT
#define GPIO_PS3V3_EN_DEFAULT       GPIO_PIN_0

#define GPIO_PS5V0_EN_PORT          GPIO_PORTM_BASE
#define GPIO_PS5V0_EN_PIN           GPIO_PIN_1
#define GPIO_PS5V0_EN_DIR           GPIO_DIR_MODE_OUT
#define GPIO_PS5V0_EN_DEFAULT       GPIO_PIN_1     //PIN 7 ON 5B91  //PIN 4 on 9B96

#define GPIO_SPI_N_SS0_PORT         GPIO_PORTA_BASE
#define GPIO_SPI_N_SS0_PIN          GPIO_PIN_3
#define GPIO_SPI_N_SS0_DIR          GPIO_DIR_MODE_OUT
#define GPIO_SPI_N_SS0_DEFAULT      GPIO_PIN_3

#define GPIO_TEST_MODE_PORT         GPIO_PORTD_BASE
#define GPIO_TEST_MODE_PIN          GPIO_PIN_5
#define GPIO_TEST_MODE_DIR          GPIO_DIR_MODE_IN
#define GPIO_TEST_MODE_DEFAULT      DEFAULT_NOT_USED

#define GPIO_BATT_MON_PORT          GPIO_PORTE_BASE
#define GPIO_BATT_MON_PIN           GPIO_PIN_1
#define GPIO_BATT_MON_DIR           GPIO_DIR_MODE_OUT
#define GPIO_BATT_MON_DEFAULT       ~GPIO_PIN_1

#define GPIO_BUZZ_AMP_PORT          GPIO_PORTD_BASE
#define GPIO_BUZZ_AMP_PIN           GPIO_PIN_2
#define GPIO_BUZZ_AMP_DIR           GPIO_DIR_MODE_OUT
#define GPIO_BUZZ_AMP_DEFAULT       ~GPIO_PIN_2

#define GPIO_BATT_S1_PORT           GPIO_PORTH_BASE
#define GPIO_BATT_S1_PIN            GPIO_PIN_0
#define GPIO_BATT_S1_DIR            GPIO_DIR_MODE_IN
#define GPIO_BATT_S1_DEFAULT        DEFAULT_NOT_USED

#define GPIO_BATT_S2_PORT           GPIO_PORTH_BASE
#define GPIO_BATT_S2_PIN            GPIO_PIN_1
#define GPIO_BATT_S2_DIR            GPIO_DIR_MODE_IN
#define GPIO_BATT_S2_DEFAULT        DEFAULT_NOT_USED

#define GPIO_HARD_REV_B0_PORT       GPIO_PORTM_BASE
#define GPIO_HARD_REV_B0_PIN        GPIO_PIN_3
#define GPIO_HARD_REV_B0_DIR        GPIO_DIR_MODE_IN
#define GPIO_HARD_REV_B0_DEFAULT    DEFAULT_NOT_USED

#define GPIO_HARD_REV_B1_PORT       GPIO_PORTM_BASE
#define GPIO_HARD_REV_B1_PIN        GPIO_PIN_4
#define GPIO_HARD_REV_B1_DIR        GPIO_DIR_MODE_IN
#define GPIO_HARD_REV_B1_DEFAULT    DEFAULT_NOT_USED

#define GPIO_HARD_REV_B2_PORT       GPIO_PORTM_BASE
#define GPIO_HARD_REV_B2_PIN        GPIO_PIN_5
#define GPIO_HARD_REV_B2_DIR        GPIO_DIR_MODE_IN
#define GPIO_HARD_REV_B2_DEFAULT    DEFAULT_NOT_USED

#define GPIO_HARD_REV_B3_PORT       GPIO_PORTM_BASE
#define GPIO_HARD_REV_B3_PIN        GPIO_PIN_6
#define GPIO_HARD_REV_B3_DIR        GPIO_DIR_MODE_IN
#define GPIO_HARD_REV_B3_DEFAULT    DEFAULT_NOT_USED

#define GPIO_USB_INTERRUPT_PORT		GPIO_PORTQ_BASE
#define GPIO_USB_INTERRUPT_PIN		GPIO_PIN_6
#define GPIO_USB_INTERRUPT_DIR		GPIO_DIR_MODE_IN
#define GPIO_USB_INTERRUPT_DEFAULT	DEFAULT_NOT_USED

#define GPIO_ISOLATOR_ENABLE_PORT GPIO_PORTF_BASE
#define GPIO_ISOLATOR_ENABLE_PIN GPIO_PIN_4
#define GPIO_ISOLATOR_ENABLE_DIR GPIO_DIR_MODE_OUT
#define GPIO_ISOLATOR_ENABLE_DEFAULT GPIO_PIN_4

void ECG_Gpio_Poweron(void);
void ECG_Gpio_Init();
#endif
