#ifndef __ECG_BUTTON_H__
#define __ECG_BUTTON_H__

#define POWER_PAIR_BUTTON_BASE      GPIO_PSWITCH_PORT
#define POWER_PAIR_BUTTON_PIN       GPIO_PSWITCH_PIN

#define POWER_PAIR_TIMER_BASE       TIMER3_BASE

#define PAIR_TIMER                  TIMER_A
#define PAIR_TIMER_TIMEOUT          TIMER_TIMA_TIMEOUT

#define POWER_TIMER                 TIMER_B
#define POWER_TIMER_TIMEOUT         TIMER_TIMB_TIMEOUT

#define POWER_PAIR_PRESCALE         0xfa
#define POWER_PAIR_TICKS_PER_MSEC   320
#define POWER_PAIR_MSEC_PER_INT     200
#define POWER_PAIR_TICKS_PER_INT    64000 //(320 * 200)
#define POWER_PAIR_INTS_PER_SEC     1000 / POWER_PAIR_MSEC_PER_INT
#define POWER_PAIR_INTS_PER_1_SEC   1 * POWER_PAIR_INTS_PER_SEC
#define POWER_PAIR_INTS_PER_3_SEC   3 * POWER_PAIR_INTS_PER_SEC
#define POWER_PAIR_INTS_PER_30_SEC  30 * POWER_PAIR_INTS_PER_SEC
#define POWER_PAIR_INTS_PER_60_SEC  60 * POWER_PAIR_INTS_PER_SEC

void ECG_Button_Init();

#endif


