#include <string.h>
#include "sapphire_pub.h"

#include "inc/hw_gpio.h"
#include "gpio.h"
#include "ecg_gpio.h"
#include "sysctl.h"


/* Public - Enables the GPIO Peripherals.
 * 
 * Examples
 * 
 *      ECG_Gpio_Poweron();
 * 
 * Returns nothing.
 */
void ECG_Gpio_Poweron(void)
{
    /* Enable all GPIO Peripherals */
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOC);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOE);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOG);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOH);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOJ);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOL);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOM);
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOQ);
} /* ECG_Gpio_Poweron() */


/* Public - Initializes the GPIO used by the device.
 * 
 * Examples
 * 
 *      ECG_Gpio_Init()
 * 
 * Returns nothing
 */
void ECG_Gpio_Init()
{
    GPIODirModeSet(GPIO_PSWITCH_PORT, GPIO_PSWITCH_PIN, GPIO_PSWITCH_DIR);
    GPIOPadConfigSet(GPIO_PSWITCH_PORT, GPIO_PSWITCH_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_PSWITCH_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_PSWITCH_PORT, GPIO_PSWITCH_PIN, GPIO_PSWITCH_DEFAULT);
        
	GPIODirModeSet(GPIO_ADS_N_CS_PORT, GPIO_ADS_N_CS_PIN, GPIO_ADS_N_CS_DIR);
    GPIOPadConfigSet(GPIO_ADS_N_CS_PORT, GPIO_ADS_N_CS_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_ADS_N_CS_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_ADS_N_CS_PORT, GPIO_ADS_N_CS_PIN, GPIO_ADS_N_CS_DEFAULT);
        
    //
    // Now modifiy the configuration of the pins that we unlocked.
    // Note that the DriverLib GPIO functions may need to access
    // registers protected by the lock mechanism so these calls should
    // be made while the lock is open here.
    //
            
    GPIODirModeSet(GPIO_ADS_N_DRDY_PORT, GPIO_ADS_N_DRDY_PIN, GPIO_ADS_N_DRDY_DIR);
    GPIOPadConfigSet(GPIO_ADS_N_DRDY_PORT, GPIO_ADS_N_DRDY_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_ADS_N_DRDY_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_ADS_N_DRDY_PORT, GPIO_ADS_N_DRDY_PIN, GPIO_ADS_N_DRDY_DEFAULT);
            
    GPIODirModeSet(GPIO_ADS_N_RESET_PORT, GPIO_ADS_N_RESET_PIN, GPIO_ADS_N_RESET_DIR);
    GPIOPadConfigSet(GPIO_ADS_N_RESET_PORT, GPIO_ADS_N_RESET_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_ADS_N_RESET_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_ADS_N_RESET_PORT, GPIO_ADS_N_RESET_PIN, GPIO_ADS_N_RESET_DEFAULT);
        
    GPIODirModeSet(GPIO_BT_N_SHDN_PORT, GPIO_BT_N_SHDN_PIN, GPIO_BT_N_SHDN_DIR);
    GPIOPadConfigSet(GPIO_BT_N_SHDN_PORT, GPIO_BT_N_SHDN_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
    if(GPIO_BT_N_SHDN_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_BT_N_SHDN_PORT, GPIO_BT_N_SHDN_PIN, GPIO_BT_N_SHDN_DEFAULT);
        
    GPIODirModeSet(GPIO_SPI_N_SS0_PORT, GPIO_SPI_N_SS0_PIN, GPIO_SPI_N_SS0_DIR);
    GPIOPadConfigSet(GPIO_SPI_N_SS0_PORT, GPIO_SPI_N_SS0_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_SPI_N_SS0_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_SPI_N_SS0_PORT, GPIO_SPI_N_SS0_PIN, GPIO_SPI_N_SS0_DEFAULT);
        
    GPIODirModeSet(GPIO_TEST_MODE_PORT, GPIO_TEST_MODE_PIN, GPIO_TEST_MODE_DIR);
    GPIOPadConfigSet(GPIO_TEST_MODE_PORT, GPIO_TEST_MODE_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_TEST_MODE_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_TEST_MODE_PORT, GPIO_TEST_MODE_PIN, GPIO_TEST_MODE_DEFAULT);
        
    GPIODirModeSet(GPIO_BATT_MON_PORT, GPIO_BATT_MON_PIN, GPIO_BATT_MON_DIR);
    GPIOPadConfigSet(GPIO_BATT_MON_PORT, GPIO_BATT_MON_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_BATT_MON_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_BATT_MON_PORT, GPIO_BATT_MON_PIN, GPIO_BATT_MON_DEFAULT);
        
    GPIODirModeSet(GPIO_BUZZ_AMP_PORT, GPIO_BUZZ_AMP_PIN, GPIO_BUZZ_AMP_DIR);
    GPIOPadConfigSet(GPIO_BUZZ_AMP_PORT, GPIO_BUZZ_AMP_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_BUZZ_AMP_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_BUZZ_AMP_PORT, GPIO_BUZZ_AMP_PIN, GPIO_BUZZ_AMP_DEFAULT);
        
    GPIODirModeSet(GPIO_BATT_S1_PORT, GPIO_BATT_S1_PIN, GPIO_BATT_S1_DIR);
    GPIOPadConfigSet(GPIO_BATT_S1_PORT, GPIO_BATT_S1_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_BATT_S1_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_BATT_S1_PORT, GPIO_BATT_S1_PIN, GPIO_BATT_S1_DEFAULT);
        
    GPIODirModeSet(GPIO_BATT_S2_PORT, GPIO_BATT_S2_PIN, GPIO_BATT_S2_DIR);
    GPIOPadConfigSet(GPIO_BATT_S2_PORT, GPIO_BATT_S2_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    if(GPIO_BATT_S2_DIR == GPIO_DIR_MODE_OUT)
        GPIOPinWrite(GPIO_BATT_S2_PORT, GPIO_BATT_S2_PIN, GPIO_BATT_S2_DEFAULT);
    
    GPIODirModeSet(GPIO_HARD_REV_B0_PORT, GPIO_HARD_REV_B0_PIN, GPIO_HARD_REV_B0_DIR);
    GPIOPadConfigSet(GPIO_HARD_REV_B0_PORT, GPIO_HARD_REV_B0_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
    
    GPIODirModeSet(GPIO_HARD_REV_B1_PORT, GPIO_HARD_REV_B1_PIN, GPIO_HARD_REV_B1_DIR);
    GPIOPadConfigSet(GPIO_HARD_REV_B1_PORT, GPIO_HARD_REV_B1_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
    
    GPIODirModeSet(GPIO_HARD_REV_B2_PORT, GPIO_HARD_REV_B2_PIN, GPIO_HARD_REV_B2_DIR);
    GPIOPadConfigSet(GPIO_HARD_REV_B2_PORT, GPIO_HARD_REV_B2_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);
    
    GPIODirModeSet(GPIO_HARD_REV_B3_PORT, GPIO_HARD_REV_B3_PIN, GPIO_HARD_REV_B3_DIR);
    GPIOPadConfigSet(GPIO_HARD_REV_B3_PORT, GPIO_HARD_REV_B3_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);

	GPIODirModeSet(GPIO_USB_INTERRUPT_PORT, GPIO_USB_INTERRUPT_PIN, GPIO_USB_INTERRUPT_DIR);
	GPIOPadConfigSet(GPIO_USB_INTERRUPT_PORT, GPIO_USB_INTERRUPT_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);	
//

/*
	GPIODirModeSet(GPIO_ISOLATOR_ENABLE_PORT, GPIO_ISOLATOR_ENABLE_PIN, GPIO_ISOLATOR_ENABLE_DIR);
	GPIOPadConfigSet(GPIO_ISOLATOR_ENABLE_PORT, GPIO_ISOLATOR_ENABLE_PIN, GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
	if(GPIO_ISOLATOR_ENABLE_DIR == GPIO_DIR_MODE_OUT)
		GPIOPinWrite(GPIO_ISOLATOR_ENABLE_PORT, GPIO_ISOLATOR_ENABLE_PIN, GPIO_ISOLATOR_ENABLE_DEFAULT);
*/
} /* Ecg_Gpio_Init() */
